<?php

define('DIGITALMEASURES_BASE_URL', 'https://www.digitalmeasures.com');

/**
 * Implements hook_menu().
 */
function digitalmeasures_menu() {
  $items['admin/config/services/digitalmeasures'] = array(
    'title' => 'Digital Measures Configuration',
    'access arguments' => array('admininster digital measures'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('digitalmeasures_admin_config_form'),
    'file' => 'digitalmeasures.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function digitalmeasures_permission() {
  return array(
    'administer digital measures' =>  array(
      'title' => t('Administer Digital Measures'),
      'description' => t('Perform administration tasks for the Digital Measures module.'),
    ),
  );
}

/**
 * Public function to retrieve user profile information from Digital Measures.
 */
function digitalmeasures_digitalmeasures_user_profiles($usernames = array()) {
  $resource_id = 'login/service/v4/SchemaData/INDIVIDUAL-ACTIVITIES-University';
  $arguments['USERNAME'] = $usernames;
  $response = _digitalmeasures_connect($resource_id, $arguments);
  $profiles = _digitalmeasures_xml_to_array($response->data);

  ddl($profiles);
  return $profiles;
}

/**
 * Public function to retrieve a list of all indexes and entries.
 */
function digitalmeasures_digitalmeasures_get_all_indexes() {
  $resource_id = 'login/service/v4/SchemaIndex/INDIVIDUAL-ACTIVITIES-University';
  $response = _digitalmeasures_connect($resource_id);
  $profiles = _digitalmeasures_xml_to_array($response->data);

  ddl($profiles);
  return $profiles;
}

/**
 * Helper function for connecting to Digital Measures via the drupal_http_request().
 * $arguments:    An array of options that are keyed by optional SchemaKey and
 *                whos nested array is a list of IndexKeyEntryKeys.
 * $resource_id:  The resource endpoint in Digital Measures.
 * $options:      Options peramter from for the drupal_http_request().
 */
function _digitalmeasures_connect($resource_id = '', $arguments = array(), $options = NULL) {
  $base_url = variable_get('digitalmeasures_url', '');
  $username = variable_get('digitalmeasures_username', '');
  $password = variable_get('digitalmeasures_password', '');
  $arguments = _digitalmeasures_argument_array_to_string($arguments);

  // Encode the username and password and set it in the header.
  $username_password = $username . ':' . $password;
  $options['headers']['Authorization'] = 'Basic ' . base64_encode($username_password);

  // Add the correct base_url
  $url = $base_url . '/' . $resource_id . '/' . $arguments;

  // Attempt to connect to Digital Measures
  if ($base_url && $username && $password) {
    return drupal_http_request($url, $options);
  }
  else {
    watchdog('digitalmeasures', 'Digital Measures is attempting to connect
      without the proper credentials. Please enter them on the Digital Measures
      configuration page.', array(), WATCHDOG_ERROR);
    return 'fail';
  }
}

/**
 * Helper function to convert an argument array to a comma spearated string.
 */
function _digitalmeasures_argument_array_to_string($arguments) {
  // Add the IndexEntryKey in front of the IndexKeyEntryKey in the array
  $arguments_string = '';
  foreach ($arguments as $index_entry_key => $argument_array) {
    foreach ($argument_array as $key => $index_key_entry_key) {
      $arguments_string .= $index_entry_key . ':' . $index_key_entry_key . ',';
    }
  }

  return $arguments_string;
}

/**
 * Helper function to convert an xml string to php array.
 */
function _digitalmeasures_xml_to_array($xml_string) {
  $xml = simplexml_load_string($xml_string);
  $json = drupal_json_encode($xml);
  $array = drupal_json_decode($json);

  return $array;
}
